name: Build and Deploy to k8s
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
                docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                version: latest

            - name: Set kubeconfig
              run: |
                mkdir -p ~/.kube
                echo "${{ secrets.KUBECONFIG }}"> ~/.kube/config

            - name: Deploy to kuberenetes
              run: |
                kubectl apply -f flask-deployment.yaml
                kubectl apply -f flask-service.yaml

            - name: Force rollout
              run: |
                kubectl rollout restart deployment flask-app
